variable "rgs" {}
variable "vnets" {}
variable "subnets" {}
variable "pips" {}
variable "nics" {}
variable "nsg" {}
variable "security_rule" {}
variable "nsgass" {}
variable "vms" {}
variable "bastions" {}
variable "app_gateway" {}
variable "mysqlsvrs" {}
variable "sqldbs" {}
